# action.yml
name: 'OpenSCAD Build Action'
description: 'Use OpenSCAD CLI to automatically generate artifacts in Github Actions'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  input-file:
    description: 'OpenSCAD source file'
    required: true
  output-file:
    description: 'Name of the output file (stl, off, amf, 3mf, csg, dxf, svg, png, echo, ast, term, nef3, nefdbg)'
    required: true
    default: 'output.stl'
  customizer-parameter-file:
    description: 'Path to the customizer json parameter file'
    required: false
  customizer-parameter-set:
    description: 'Name of the parameter set to use from the customizer file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-file }}
    - ${{ inputs.output-file }}
    - ${{ inputs.customizer-parameter-file }}
    - ${{ inputs.customizer-parameter-set }}
